### ISSUE TITLE
Is there a way to use rust to build a custom action for the wix installer ?

### ISSUE THREAD

**Issue by 2ndTaleStudio** [volks73/cargo-wix#100]
Hi there,

I know it's more a question rather than an issue, but is there a way to create custom actions for the installer with Rust? I've seen several "tutorial" discussing VisualStudio projects covering either C++ or C# to build those things. I was wondering if the same would be possible with Rust ?

Thanks in advance for any hint..

**Comment by volks73** [comment]
I only did some very short investigation into custom actions, generally. It appears the most common process for creating a custom action is to write it in C# and generate a DLL. I am not sure if the built DLL is actually a DLL or an Assembly. If it is an actual DLL, then it might be possible because it is possible to create DLLs with Rust. I found [this demo project](https://github.com/rkarp/rust-dll-demo) by @rkarp that shows how to create a Windows DLL with Rust that could be useful as a starting point. I am not sure how the C# entry point and classes translates to a Rust DLL. I do wonder if there is another crate in here...

You mention finding examples of creating custom actions in C++. Generally, if C++ can do it, so can Rust. Depending on the complexity of the C++, there might be some hope in taking a C++ example and converting it to Rust. This would be more trial and error.

Another option might be to create a C# wrapper DLL and have the wrapper DLL call the Rust code. C# can call/import external code through DLLs,. I found [this blog post](https://dev.to/living_syn/calling-rust-from-c-6hk) on calling Rust from C#. This might be quickest and easiest way to it, but it would require C# knowledge and programming, at which point, it might just be quicker and easier to write the custom action in C# and skip Rust altogether.

Please keep in mind, I am not very familiar with C# and/or custom actions, so all of this could be way off base.

**Comment by 2ndTaleStudio** [comment]
Hi, thanks for this quick response and the hints.. I'll check out the links you provided.
C# is not much of an option as this would add to the build complexity which I try to avoid. The application is written in Rust, the WIX tool is used to build the installer (via the smooth cargo-wix tooling). This is already some sort of complexity that need to be managed by a build pipeline, so I better try to avoid C# or any other additional different build tool as long as possible ;)

**Comment by volks73** [comment]
I agree it adds complexity, but maybe not to the building of the Rust project, per se. 

Can you create the custom action in C# as a separate project from your Rust project, build it once as a DLL using the C# tooling/Visual Studio/examples and then include the built DLL in the cargo-wix Rust project build? In other words, you would only have to create and build the C# custom action once, not every time you build the Rust project. You could include the DLL in the `wix` folder of the Rust project and reference it in the WiX Source file there as well. You could re-use the built custom action in other projects, too. This would only work if the custom action functionality was independent of the Rust project's development/functionality. Just a thought.

**Comment by 2ndTaleStudio** [comment]
Hey,
thx again. I'll give it a try :)

**Comment by volks73** [comment]
Your welcome. I am going to close this issue as I believe the original question has been answered and no changes are required or possible for this project.
