### ISSUE TITLE
Compiler-args set in the TOML override those set in the CLI

### ISSUE THREAD

**Issue by roblabla** [volks73/cargo-wix#109]
Compiler-args and linker-args specified in the TOML override those set in the CLI: https://github.com/volks73/cargo-wix/blob/master/src/create.rs#L654. This makes it impossible to test an arg change simply by passing said arg on the CLI before writing it to the TOML.

I believe either they should be merged or the CLI should be given priority over the TOML. The current behavior is very unexpected.

**Comment by volks73** [comment]
You are correct, this is not the expected behavior nor consistent. This is a bug.

The CLI should always override the TOML values. Order of precedence/override, with the lower number being overwritten by higher number:

1. Hard-coded defaults
2. System configuration file (currently not really implemented)
3. User configuration file (currently not really implemented)
4. Environment variables
5. Manifest (TOML)
6. CLI argument

**Comment by volks73** [comment]
Fixed as of 37fbaa9bf2303117c686f220ffa557ee77474346
