### ISSUE TITLE
Unknown 'sk-sk' culture

### ISSUE THREAD

**Issue by cstkingkey** [volks73/cargo-wix#147]
running cargo wix -c sk-SK

**Comment by volks73** [comment]
Thank you for the issue submission. I was able to track down the source of this bug and I have recently pushed a commit (9f787f8f3060b0078b8a8498fd5bb30046175482) that should resolve this issue. The issue was a uppercase patterns for some of the cultures were used but the pattern matching was done with lowercase input. Additional unit tests were added. Assuming some testing works. I will create a bugfix release shortly.
