### ISSUE TITLE
signtool complain about missing /fd flag

### ISSUE THREAD

**Issue by cstkingkey** [volks73/cargo-wix#149]
SignTool Error: No file digest algorithm specified. Please specify the digest algorithm with the /fd flag. Using /fd SHA256 is recommended and more secure than SHA1. Calling signtool with /fd sha1 is equivalent to the previous behavior. In order to select the hash algorithm used in the signing certificate's signature, use the /fd certHash option.
Error[1] (Command): The 'signtool' application failed with exit code = 1

**Comment by volks73** [comment]
Thank you for submitting this issue and sharing the error message. What version of the Windows SDK and SignTool are you using?

I will admit. I have not used this feature since the original creation of this Cargo sub-command (v0.1.0, ~2017). At that time, it seemed to work as long as the SignTool was available in the path. I only implemented a minimum amount of functionality for my personal use. This appears to be the first, non-me usage of the signing feature, so can you provide a little more information on your use case and your environment?

The error message seems to indicate that newer versions of the [SignTool from Microsoft](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe) have changed required flags. The requirement for the `/fd` flag was not present in ~2017.

**Comment by cstkingkey** [comment]
I'm using win sdk 10.0.22000.0, and signtool version is 10.0.22000.194
signtool   do not require fd flag, but can accpet it.
So adding the flag unconditionally solve the issue. 
Since 10.0.14393.795 vesion signtool is released in 2017 which is pretty old, I think this flags will not make any trouble.
