### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by Gankra** [volks73/cargo-wix#231]
Just noticed https://volks73.github.io/cargo-wix is down, just wanted to give you a heads up in case you didn't notice.

**Comment by volks73** [comment]
This should be fixed. rustdoc changed the output structure for documentation since the last time I updated the documentation, i.e. ran `cargo doc`. I had removed the `index.html` file from the root folder to clean up the documentation.

However, a minimal `index.html` file is needed in the root folder for GitHub Pages to work. I have added back in the redirecting `index.html` file "hack" for GitHub.

This should not be an issue for the docs.rs documentation, but docs.rs only hosts the library documentation.
