### ISSUE TITLE
Option to suppress generation of .wixpdb

### ISSUE THREAD

**Issue by slonopotamus** [volks73/cargo-wix#82]
Currently, cargo-wix produces .wixpdb file in the same dir as .msi. This is unconvenient when user wants to build msi into a directory whose whole contents are then deployed to GitHub Releases or something similar.

`light.exe` has `-spdb` command-line switch that suppresses generation of .wixpdb file, however I failed to find how it can be passed through cargo-wix.

**Comment by volks73** [comment]
I never noticed that option before for the `light.exe` application. I am not sure why the `.wixpdb` file is ever really needed as I believe it is mostly a build artifact of the MSI file. Thus, I would actually make suppression the default.

The relevant section is in the `src\create.rs` file around line 311.

I currently do not have any option or way to pass through arguments to the candle or light application. This should probably be a separate issue/feature request.

**Comment by volks73** [comment]
Although, there is still the `.wixobj` file that is needed and exists in the same folder, which probably would cause problems with automated builds/deployment.

I do not see a suppression option in the `candle` nor `light` applications, which I am not surprised because this file is needed as the input for the `light` application. 

Another feature might be to add a flag to the create (default) command that deletes the .wixobj file after successful creation of the MSI. A `--delete-wixobj` flag. The cargo-wix application could delete the artifact, but maybe automated build tools can handle this? I am not familiar enough to know.

**Comment by slonopotamus** [comment]
I think, `.wixobj` always goes to `target/wix`, so it isn't a problem.

**Comment by volks73** [comment]
You maybe interested in 5ddd93538e3bf8d88d17fbd493e16bd309cad3ca, which suppresses the wixpdb file by default now.

**Comment by slonopotamus** [comment]
Thank you, this change combined with #79 allows me to produce MSI in a staging directory that later goes to GitHub Releases cleanly without any intermediate build artifacts.
