### ISSUE TITLE
Dash in Ids cause candle to error out

### ISSUE THREAD

**Issue by brookst** [volks73/cargo-wix#89]
`cargo wix init` seems to generate element Ids that are not accepted by `candle`. Compiling with `cargo wix` gives errors like:

    crate-name\wix\main.wxs(XX) : error CNDL0014 :
    The Component/@Id attribute's value, 'crate-nameBinary', is not a legal identifier.
    Identifiers may contain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).
    Every identifier must begin with either a letter or an underscore.

    crate-name\wix\main.wxs(XX) : error CNDL0014 :
    The File/@Id attribute's value, 'crate-nameEXE', is not a legal identifier.
    Identifiers may contain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).
    Every identifier must begin with either a letter or an underscore.

    crate-name\wix\main.wxs(XX) : error CNDL0014 :
    The ComponentRef/@Id attribute's value, 'crate-nameBinary', is not a legal identifier.
    Identifiers may contain ASCII characters A-Z, a-z, digits, underscores (_), or periods (.).
    Every identifier must begin with either a letter or an underscore.

    Error[1] (Command): The 'candle' application failed with exit code = 14.

Rust [doesn't have a firm convention on naming](https://github.com/rust-lang-nursery/api-guidelines/issues/29), but could dashes be normalized out for Ids?

**Comment by brookst** [comment]
Looking at this, it seems like another string (binary-norm?) could be passed through to the template at [`src/print/wxs.rs#L289`](https://github.com/volks73/cargo-wix/blob/c8fa5e114637f1c997fd931a64a538317843ecde/src/print/wxs.rs#L289). That could be used in the substitutions for Ids. `str::replace` ought to work just to swap out dashes for underscores.

**Comment by volks73** [comment]
Thank you for the issue and idea. I would be happy to accept a pull request that implements the normalization you suggest. Some documentation about the feature would be needed since it would be doing some "magic" on behalf of the user. Maybe there also needs to be a CLI flag: `--no-name-mangling` or `--no-name-normalization` or `--skip-normalization`, etc. to turn off the "magic" if needed?

However, there are the [-B,--binary](https://volks73.github.io/cargo-wix/cargo_wix/index.html#-b--binary) and/or [-n,--name](https://volks73.github.io/cargo-wix/cargo_wix/index.html#-n--name) options for the `cargo wix init`, `cargo wix` (default), and `cargo wix print` commands, respectively. Do these options serve the same purpose and can they be used to resolve the issue?

An alternative could to simply generate the IDs in some programmatic manner that avoids using the crate name field. Instead of concatenating the crate name with "Binary" and "EXE", could we just have "binary1" and "exe1". We do not really care about the actual content of the IDs do we?

**Comment by volks73** [comment]
>An alternative could be to simply generate the IDs in some programmatic manner that avoids using the crate name field. Instead of concatenating the crate name with "Binary" and "EXE", could we just have "binary1" and "exe1". We do not really care about the actual content of the IDs do we?

On further thought, this is the right way to go. I have changed the implementation for generating IDs for the binaries to eliminate the usage of the crate name. This avoids having to add any CLI flags/options or worry about normalizing strings. This also works better with the new changes for multiple binaries.

Closed as of e4e9d35039fda37678c971faf889650d3f1d58aa
