### ISSUE TITLE
Msi Installed program does not have color support

### ISSUE THREAD

**Issue by Songtronix** [volks73/cargo-wix#90]
I'm unsure about what exactly is causing that. It may be wix, cargo-wix specific or my main.wxs settings or anything really.
If I run it myself everything works fine. But if it is installed via the msi installer colors do not work (they do for spawned subprocesses for whatever reason).

**OS**: Windows 10
**Logging crate**: [fern](https://crates.io/crates/fern) (with colored feature).

![grafic](https://user-images.githubusercontent.com/18618951/66701237-601cf380-ecfa-11e9-9cce-84887275c2ac.png)

**Comment by volks73** [comment]
I wonder if this is related to a Debug versus Release profile build? The cargo-wix subcommand builds the MSI using the Release profile. When you run everything yourself, are you running the Debug profile version?

Can you try the creating the MSI with the [--no-build](https://volks73.github.io/cargo-wix/cargo_wix/index.html#--no-build) flag?

I am not familiar with [fern](https://crates.io/crates/fern) and its coloring feature, but it is only recently that the Windows 10 command prompt started supporting ANSI terminal escape codes, and it's support for ANSI escape codes has to be explicitly turned on. [There is a good discussion and information about Windows 10 color support](https://github.com/ogham/rust-ansi-term/issues/31) related to the [ansi_term](https://crates.io/crates/ansi_term) crate. The fern crate appears to use the [colored](https://crates.io/crates/colored) crate, which has the following (closed) issue: [Colours don't work in command prompt on Windows](https://github.com/mackwic/colored/issues/56).

I will note early versions of this subcommand did use the `ansi_term` crate as well, but due to issues with coloring and support for older versions of Windows 7/10, I switched to using the [termcolor](https://crates.io/crates/termcolor) crate, which supports the "native" Windows command prompt coloring API, but it is a little more cumbersome to use than the other terminal coloring crates because of this support. FYI, this is the same crate used by Cargo for coloring.

Given this information, I would suspect the issue is originating outside of the cargo-wix subcommand, and it is not a bug for this project. However, it does highlight a missing feature in using a different build profile other than the Release profile. A CLI flag or option should probably be added to the default cargo-wix subcommand (create) to allow alternative build profiles, in addition to just skipping the build step before MSI compiling.

**Comment by Songtronix** [comment]
Thank you for the detailed answer!
I've just tried debug and release. Both work on my machine fine without the installer.
With the installer it does not. Neither release nor debug (via --no-build).

I've tested as described in the issue to enable the virtual terminal for windows support and now it works perfectly fine! I'll try to get a fix merged in fern.

Thank you so much!
